### PR TITLE
Issue 111

### PR DESCRIPTION
**Pull request by JavaTheHood**
I added an option to the promt, when the app is scaffolded.
If 'coffescript' is choosen as the appScript language,
the user can choose to use the classes syntax. The default is yes.

I then modified the templates for _controller.coffee, _directive.coffee,
_factory.coffee and _service.coffee, all with an condition. If the
classes option was choosen, then the template will contain a
coffeescript class. Otherwise it will generate a file with the 'old'
syntax.

Home-controller with the new classes syntax:
```coffee
'use strict'

###
 # @ngdoc object
 # @name home.controller:HomeCtrl
 #
 # @description
 #
###

class HomeCtrl
  constructor: ->
    @ctrlName = 'HomeCtrl'

angular
  .module('home')
  .controller 'HomeCtrl', [HomeCtrl]
```

A service:
```coffee
'use strict'

###
 # @ngdoc service
 # @name home.service:Home
 #
 # @description
 #
###

class Home
  constructor: ->
    @name = 'Home'

  get: ->
    @name

angular
  .module 'home'
  .service 'Home', [Home]
```

A directive:
```coffee
'use strict'
###
 # @ngdoc directive
 # @name home.directive:home
 # @restrict EA
 # @element
 #
 # @description
 #
 # @example
   <example module="home">
     <file name="index.html">
      <home></home>
     </file>
   </example>
 #
###

class Home
  constructor: ->
    return {
      restrict: 'AE'
      scope: {}
      templateUrl: 'home/home-directive.tpl.html'
      replace: false
      controllerAs: 'home'
      controller: ->
        vm = @
        vm.name = 'home'
      link: (scope, element, attrs) ->
        ###jshint unused:false ###
    }

angular
  .module 'home'
  .directive 'home', [Home]

```
A factory:
```coffee
'use strict'

###
 # @ngdoc service
 # @name home.factory:Home
 #
 # @description
 #
###

class Home
  @instance = undefined
  @someValue = 'Home'
  constructor: ->
    if @instance then @instance else @instance = @

  @someMethod: ->
    'Home'

angular
  .module 'home'
  .factory 'Home', [Home]
```
Currently there is no Typescript support available. I suggest to open an
issue for that.

Best regards from Germany

Roman

### CODE REVIEW

**Comment by dustinspecker** [comment]
Thanks again! This looks great! What are your thoughts on dropping the non-class syntax completely? I'd completely support dropping non-class because I think we should encourage it and I'd also like to work on reducing the number of questions ng-poly asks (already way too many in my opinion).

**Comment by JavaTheHood** [comment]
Full support on that point! I'd also use the same language for scripting and testing (except in the case of typescript).

**Comment by JavaTheHood** [comment]
Classes syntax is now used by defauld

**Comment by JavaTheHood** [comment]
Any updates?

**Comment by dustinspecker** [comment]
Sorry, I've been pretty busy. This looks good to me. If you update this with master and I'll get this PR merged in.

Thank you!

**Comment by dustinspecker** [comment]
Looks good. Thanks!

**Pull request merged**
