### PR TITLE
Issue 62 - Angular Material Support

### PR DESCRIPTION
**Pull request by RomanCPodolski**
Angular Material is available as a framework-choise, when ngversion > 1.3.*.

### CODE REVIEW

**Comment by dustinspecker** [comment]
This is good, but I would also like add a simple navigation using Angular Material in the _index.{haml,html,jade} files - just to be consistent with the other frameworks. I haven't used Angular Material much, so maybe that's not as simple, which case we can merge this as it is.

**Comment by JavaTheHood** [comment]
I take a look at it.

**Comment by dustinspecker** [comment]
https://github.com/angular/material-start/tree/es5-tutorial This might be a good starting point. I'll look into this, too.

**Comment by coldacid** [comment]
How well does this integrate with the existing unit test task in gulp? From a look at the diffs, it doesn't seem like the mocks for angular-material will get added in, unlike the default angular mocks.

**Comment by dustinspecker** [comment]
I'm going to close this PR because it's inactive. Feel free to re-open if anyone wants to continue on this work.

**Pull request closed without merging**
