### PR TITLE
Issue 316

### PR DESCRIPTION
**Pull request by Jeffarese**
#### What does this PR do?
This changes the way directives are created to use TypeScript classes when using the **controllerAs** syntax.

If the project uses **controllerAs** syntax, it creates the class and binds it as a controller to the directive object.

If the project don't use **controllerAs** syntax, it just creates the function as before, but creates the custom scope typing as an interface, extending the ng.IScope object.

#### Where should the reviewer start?
It should see that the directives are now using classes when using **controllerAs**

#### How should this be manually tested?
- Create a new project
- Select **TypeScript** and **controllerAs** 
- Create a new directive 
- Check that the created directive is using a class as a controller, which has a **name** and **$inject** properties.
- Check that the directive  works correctly and can be used in a template

- Create a new project
- Select **TypeScript** and NOT **controllerAs** 
- Create a new directive 
- Check that the created directive is uses a function, with the proper Interface created for the typedef

#### Documents
Example of a directive named **exampleComponent** created with **controllerAs** syntax:

screenshot from 2016-06-02 12-41-47

### CODE REVIEW

**Comment by dustinspecker** [comment]
Thank you so much for this pull request! I really, really appreciate the work put into it and the description!

I'll try to review this later tonight/tomorrow. I apologize for the delay.

**Comment by Jeffarese** [comment]
You're welcome :wink: 

I'm using this generator on a big SPA with Angular 1.x and TypeScript and I want to help a little with the TypeScript support :smile:

**Comment by dustinspecker** [comment]
Thank you very much for this PR! I apologize for the very late delay in getting this merged.

This has been rebased into master and will be released as soon as CI passes.

**Comment by jeffarese** [comment]
No problem ;) happy to provide a little support!

**Pull request closed without merging**
